project_id = "emmogpqoqfmwtipxwcit"

[functions.send-lead-to-monday]
verify_jwt = false

[functions.seed-materials]
verify_jwt = false

[functions.save-visit-request]
verify_jwt = false

[functions.update-overdue-status]
verify_jwt = false

[functions.list-users]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false
